FROM centos

RUN yum install -y epel-release && \
    yum install -y yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm && \
    yum update -y && \
    yum install -y virt-what salt-minion && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN sed -i "s|#master: salt|master: mom|g" /etc/salt/minion
RUN sed -i "s|#environment: None|environment: mom|g" /etc/salt/minion


ENTRYPOINT ["salt-minion", "-l", "debug"]


